### PR TITLE
Enhance extraction to preserve obsolete strings

### PR DESCRIPTION
**Pull request by gmartin7**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/xliffforhtml/22)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/xliffforhtml/22)* status: all files reviewed, 6 unresolved discussions (waiting on @gmartin7)

___
*[`src/XliffForHtml/HtmlXliff.cs` line 791 at r1](https://reviewable.io/reviews/sillsdev/xliffforhtml/22#-N3txFy88t18NaQREbAR:-N3txFy88t18NaQREbAS:b9mk5m2) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/cd0dc466b89b0619a1eb56fee4c82d9b3b1dc79e/src/XliffForHtml/HtmlXliff.cs#L791)):*
> ```Smalltalk
> 		/// <summary>
> 		/// Any trans-unit elements found in the old xliff document that are missing in the new xliff document
> 		/// are copied to the new xliff document, but marked as "obsolete".
> ```

This probably deserves a "why".
Something like "This allows us to essentially maintain one set of xlf files across versions without suddenly dropping existing translations from release or beta versions. Developers can manually remove strings once they are obsolete in the release version, too."
___
*[`src/XliffForHtml/HtmlXliff.cs` line 793 at r1](https://reviewable.io/reviews/sillsdev/xliffforhtml/22#-N3tx2fm5Sy50JD2ly5R:-N3tx2fm5Sy50JD2ly5S:b633cjg) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/cd0dc466b89b0619a1eb56fee4c82d9b3b1dc79e/src/XliffForHtml/HtmlXliff.cs#L793)):*
> ```Smalltalk
> 		/// are copied to the new xliff document, but marked as "obsolete".
> 		/// </summary>
> 		public static void CopyMissingUnitsAsObsoleteToNewXliff(XmlDocument newXliff, XmlDocument oldXliff)
> ```

How do you feel about `CopyObsoleteUnitsToNewXliff`?



_Code quote:_
```Smalltalk
CopyMissingUnitsAsObsoleteToNewXliff
```
___
*[`src/XliffForHtml/HtmlXliff.cs` line 825 at r1](https://reviewable.io/reviews/sillsdev/xliffforhtml/22#-N3tuih8DWQtZArpgCXx:-N3tuih9C44LWQ3k_y2x:bb7phvt) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/cd0dc466b89b0619a1eb56fee4c82d9b3b1dc79e/src/XliffForHtml/HtmlXliff.cs#L825)):*
> ```Smalltalk
> 				// 1) cloneNode() keeps the old doc context and complains if you try to add a cloned node to the new
> 				// document.
> 				// 2) removeNamespace() apparently immediately inserts the default namespace, which was wanted either.
> ```

typo



_Code quote:_
```Smalltalk
which was wanted either
```
___
*[`src/XliffForHtml/HtmlXliff.cs` line 844 at r1](https://reviewable.io/reviews/sillsdev/xliffforhtml/22#-N3tuytK0TJA959Nkovy:-N3tuytK0TJA959Nkovz:bzhs3pz) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/cd0dc466b89b0619a1eb56fee4c82d9b3b1dc79e/src/XliffForHtml/HtmlXliff.cs#L844)):*
> ```Smalltalk
> 				{
> 					var newNoteForObsolete = newXliff.CreateElement("note");
> 					newNoteForObsolete.InnerText = "Obsolete for current Bloom";
> ```

We can't have `Bloom` here. This is a general-use program.

I'm not sure what we have access to at this point... what we really want is the version number. My guess is we don't access to that because it doesn't appear the version number in the xliff files are kept up to date.

One option would be to pass in the version number on the command line. But even getting ahold of the correct version number to pass in when Bloom runs this might not be easy.

I wonder if the correct/easiest workflow actually just looks like this:
- When a string is made obsolete, we manually add a note in the xlf file saying "Obsolete starting with 5.3" (or whatever we usually do in Bloom.xlf).
- This program knows not to remove any entries with a note containing "obsolete" (as it now doesn't).

Of course, since you've already done this work, maybe the easiest thing at this point is to let it detect an obsolete string (as it does) and insert a generic note which we then manually change before committing?

Thoughts?



_Code quote:_
```Smalltalk
Obsolete for current Bloom
```
___
*[`src/XliffForHtmlTests/TestExtractXliff.cs` line 1365 at r1](https://reviewable.io/reviews/sillsdev/xliffforhtml/22#-N3ttVxM4IoFk8HzUhXN:-N3ttVxM4IoFk8HzUhXO:booyfq) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/cd0dc466b89b0619a1eb56fee4c82d9b3b1dc79e/src/XliffForHtmlTests/TestExtractXliff.cs#L1365)):*
> ```Smalltalk
> 
> 		[Test]
> 		public void TestCopyingMissingTransUnitsFromOldXliff_CreatesObsolete()
> ```

Typically we name unit tests as MethodBeingTested_Scenario_ExpectedResult
___
*[`src/XliffForHtmlTests/TestExtractXliff.cs` line 1367 at r1](https://reviewable.io/reviews/sillsdev/xliffforhtml/22#-N3ttJRiExUzqUxPot-m:-N3ttJRiExUzqUxPot-n:b-u0lutj) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/cd0dc466b89b0619a1eb56fee4c82d9b3b1dc79e/src/XliffForHtmlTests/TestExtractXliff.cs#L1367)):*
> ```Smalltalk
> 		public void TestCopyingMissingTransUnitsFromOldXliff_CreatesObsolete()
> 		{
> 			// Create the xliff from an original HTML file to mimic program behavior.
> ```

This appears to just extract from a string, not a file.



_Code quote:_
```Smalltalk
from an original HTML file
```

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/xliffforhtml/22)* status: 3 of 5 files reviewed, 5 unresolved discussions (waiting on @andrew-polk)

___
*[`src/XliffForHtml/HtmlXliff.cs` line 791 at r1](https://reviewable.io/reviews/sillsdev/xliffforhtml/22#-N3txFy88t18NaQREbAR:-N3u-irq2cRWo4NEB6lU:b-896fix) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/cd0dc466b89b0619a1eb56fee4c82d9b3b1dc79e/src/XliffForHtml/HtmlXliff.cs#L791)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This probably deserves a "why".
Something like "This allows us to essentially maintain one set of xlf files across versions without suddenly dropping existing translations from release or beta versions. Developers can manually remove strings once they are obsolete in the release version, too."
</blockquote></details>

Done.
___
*[`src/XliffForHtml/HtmlXliff.cs` line 793 at r1](https://reviewable.io/reviews/sillsdev/xliffforhtml/22#-N3tx2fm5Sy50JD2ly5R:-N3u-yg9Bn0WmJFwAa69:b-ajec8l) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/cd0dc466b89b0619a1eb56fee4c82d9b3b1dc79e/src/XliffForHtml/HtmlXliff.cs#L793)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

How do you feel about `CopyObsoleteUnitsToNewXliff`?
</blockquote></details>

Done. No feelings one way or the other. It was Steve's accurate, but maybe a bit verbose name.
___
*[`src/XliffForHtml/HtmlXliff.cs` line 844 at r1](https://reviewable.io/reviews/sillsdev/xliffforhtml/22#-N3tuytK0TJA959Nkovy:-N3u3lnPEtCTu49tKeqg:bqcbb0h) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/cd0dc466b89b0619a1eb56fee4c82d9b3b1dc79e/src/XliffForHtml/HtmlXliff.cs#L844)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

As Andrew said, manually editing the string is the easiest way to get a program and version number into the note.  This could possibly be made a command line option, but I'm not sure how Bloom's gulp.js file would find out the version number.
</blockquote></details>

OK, for now I've made it say `Obsolete for {name} {version}` and we'll do a manual replace.
___
*[`src/XliffForHtmlTests/TestExtractXliff.cs` line 1365 at r1](https://reviewable.io/reviews/sillsdev/xliffforhtml/22#-N3ttVxM4IoFk8HzUhXN:-N3u1alZ5qY-2fhqjLdV:b-896fix) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/cd0dc466b89b0619a1eb56fee4c82d9b3b1dc79e/src/XliffForHtmlTests/TestExtractXliff.cs#L1365)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Typically we name unit tests as MethodBeingTested_Scenario_ExpectedResult
</blockquote></details>

Done.
___
*[`src/XliffForHtmlTests/TestExtractXliff.cs` line 1367 at r1](https://reviewable.io/reviews/sillsdev/xliffforhtml/22#-N3ttJRiExUzqUxPot-m:-N3u1rqJBfcPOE3jiHUx:b-2ju604) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/cd0dc466b89b0619a1eb56fee4c82d9b3b1dc79e/src/XliffForHtmlTests/TestExtractXliff.cs#L1367)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This appears to just extract from a string, not a file.
</blockquote></details>

Modified by adding "representation" here and in the test I copied it from.

**Review by gmartin7 — COMMENTED** [review]
Visual Studio (2017) asked to "normalize line endings" for `TestExtractXliff.cs` and Steve suggested using Windows when editing on Windows... that's the source of the 2nd commit.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/xliffforhtml/22#-:-N3u9F9RCFv8koy3nRy2:b-fqo8nn)* status: 3 of 5 files reviewed, 5 unresolved discussions (waiting on @andrew-polk)

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/xliffforhtml/22)* status: 3 of 5 files reviewed, 5 unresolved discussions (waiting on @andrew-polk)

___
*[`src/XliffForHtml/HtmlXliff.cs` line 791 at r1](https://reviewable.io/reviews/sillsdev/xliffforhtml/22#-N3txFy88t18NaQREbAR:-N3uAGIg00xQu0ou32ls:b-896fix) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/cd0dc466b89b0619a1eb56fee4c82d9b3b1dc79e/src/XliffForHtml/HtmlXliff.cs#L791)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

**Pull request merged**
