### PR TITLE
Initial code submission for XliffForHtml

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/xliffforhtml/1)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Looks basically good but I'm confused by ContainsTranslatableText. I haven't had time to review tests yet.

---

Reviewed 11 of 15 files at r1.
Review status: 11 of 15 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/XliffForHtml/HtmlXliff.cs, line 39 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-Kr2ZneHRNHoqktRtI1G:-Kr2ZneHRNHoqktRtI1H:b-pt54nn) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/83ce89c92edcea7919d041d40a35e7342063413c/src/XliffForHtml/HtmlXliff.cs#L39)):*
> ```Smalltalk
> 
> 		/// <summary>
> 		/// Lookup map used by the InjectTranslations method.
> ```

I find it very helpful in describing maps to say what the keys and values are (especially when they are generic things like strings).

---

*[src/XliffForHtml/HtmlXliff.cs, line 164 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-Kr2b_iOVrDO9FeCNxWj:-Kr2b_iOVrDO9FeCNxWk:b-hkoxtm) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/83ce89c92edcea7919d041d40a35e7342063413c/src/XliffForHtml/HtmlXliff.cs#L164)):*
> ```Smalltalk
> 			transUnit.SetAttribute("id", id);
> 
> 			var source = _xliffDoc.CreateElement("source");
> ```

This variable name confused me, here and in similar places. It's true that it's the source element in the xliff file, but it's the OUTPUT of this method. Would it be too verbose to call it something like "sourceEltBeingCreated"?

---

*[src/XliffForHtml/HtmlXliff.cs, line 175 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-Kr2cEYzJy636mwzGROP:-Kr2cEYzJy636mwzGROQ:blm04u9) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/83ce89c92edcea7919d041d40a35e7342063413c/src/XliffForHtml/HtmlXliff.cs#L175)):*
> ```Smalltalk
> 		}
> 
> 		private void ProcessSourceNode(XmlElement source, HtmlNode translatableNode)
> ```

This compounds with the previous comment, but it's my impression that a fairly common convention is to put input arguments before outputs, in a method that uses some arguments to output results. E.g., File.Copy(source, dest). Here source is the element that gets modified using stuff from the second argument.

---

*[src/XliffForHtml/HtmlXliff.cs, line 195 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-Kr2dLIduUfJVCpKMeul:-Kr2dLIduUfJVCpKMeum:brmqxug) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/83ce89c92edcea7919d041d40a35e7342063413c/src/XliffForHtml/HtmlXliff.cs#L195)):*
> ```Smalltalk
> 				else
> 				{
> 					var gNode = _xliffDoc.CreateElement("g");
> ```

Is it possible to summarize in a sentence or so what Oasis says about the purpose of "g" elements? (and "x" below)?

---

*[src/XliffForHtml/HtmlXliff.cs, line 241 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-Kr2e9HJPcEd0e1lModX:-Kr2e9HJPcEd0e1lModY:bm37kly) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/83ce89c92edcea7919d041d40a35e7342063413c/src/XliffForHtml/HtmlXliff.cs#L241)):*
> ```Smalltalk
> 		}
> 
> 		private void CopyHtmlAttributes(XmlElement xml, HtmlNode html, bool checkForTranslatableAttribute = false)
> ```

That last argument seems misleading, since you haven't implemented it. Maybe it allows other code to be ready for that enhancement? Anyway, if there's a reason to keep it I think it should be commented.

---

*[src/XliffForHtml/HtmlXliff.cs, line 267 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-Kr2erWis2hhXHrSrMgk:-Kr2erWis2hhXHrSrMgl:b-phhyo4) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/83ce89c92edcea7919d041d40a35e7342063413c/src/XliffForHtml/HtmlXliff.cs#L267)):*
> ```Smalltalk
> 			}
> 			// Check whether all of the children that aren't #text or #comment
> 			// are inline elements.  If so, we can create a trans-unit.
> ```

What it actually does is check that all children that are elements are either inline or wrappers, which isn't quite what the comment says. Non-elements (even if not text or comments) are ignored.
What isn't clear and I think begs for explanation is WHY an element with no text is said to contain translatable text as long as it has no inline or wrapper elements. A div, for example, is apparently neither inline nor a wrapper (though depending on CSS, divs can certainly be inline, and they usually wrap things); so an element containing nothing but an empty div would evaluate as containing translatable text. If that's intentional I'd like it explained.

---

*[src/XliffForHtml/HtmlXliff.cs, line 348 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-Kr2hQwCe4OgSRtB94so:-Kr2hQwCe4OgSRtB94sp:bmxpql6) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/83ce89c92edcea7919d041d40a35e7342063413c/src/XliffForHtml/HtmlXliff.cs#L348)):*
> ```Smalltalk
> 
> 		/// <summary>
> 		/// Check whether the named HTML element can "wrap a group".
> ```

Maybe explain a little more? I would expect, for example, that DIV and P would be considered wrappers, and maybe even span...they can certainly wrap a variety of other HTML elements.

---

*[src/XliffForHtml/HtmlXliff.cs, line 495 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-Kr2lNhxqvx0SF3V2lYE:-Kr2lNhxqvx0SF3V2lYF:b-v5v93y) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/83ce89c92edcea7919d041d40a35e7342063413c/src/XliffForHtml/HtmlXliff.cs#L495)):*
> ```Smalltalk
> 							node.SetAttributeValue("xml:lang", _targetLanguage);
> 						}
> 					}
> ```

Seems we should somehow warn the user about elements with data-i18n etc and nothing...not even original source?...in the xliff. Presumably they need to run extract again, or have altogether the wrong xliff?

---

*[src/XliffForHtml/HtmlXliff.cs, line 570 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-Kr2iwult7M3RlXHjWwM:-Kr2iwult7M3RlXHjWwN:b-s9s4dy) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/83ce89c92edcea7919d041d40a35e7342063413c/src/XliffForHtml/HtmlXliff.cs#L570)):*
> ```Smalltalk
> 				else if (attr.Name.StartsWith("html:"))
> 				{
> 					// TODO: protect against double quotes in the attribute value.
> ```

Do we actually need to do this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-:-Kr2n0-KAGI6bJw88qoJ:bppxtdt)*

**Comment by JohnThomson** [comment]
Everything you've changed looks good.
Unfortunately, it seems the comments I wrote on tests didn't get published. So I'm doing that now. Sorry. Up to you which are worth acting on.

---

Reviewed 4 of 15 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 20 unresolved discussions.

---

*[src/XliffForHtmlTests/TestExtractXliff.cs, line 29 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-Kr6G-M-7E1YUDk2xOr7:-Kr6G-M-7E1YUDk2xOr8:b-n4x8o3) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/83ce89c92edcea7919d041d40a35e7342063413c/src/XliffForHtmlTests/TestExtractXliff.cs#L29)):*
> ```Smalltalk
>  <file original=""test.html"" datatype=""html"" source-language=""en"">
>   <body>
>    <trans-unit id=""1 & 2 & 3"">
> ```

Surprises me that an XML file can have unescaped ampersands in an attribute value

---

*[src/XliffForHtmlTests/TestExtractXliff.cs, line 166 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-Kr6H9RukVXophKX8X2z:-Kr6H9RukVXophKX8X3-:b8zofmj) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/83ce89c92edcea7919d041d40a35e7342063413c/src/XliffForHtmlTests/TestExtractXliff.cs#L166)):*
> ```Smalltalk
> 
> 		[Test]
> 		public void TestClassAttribute()
> ```

It's not obvious what you're testing about the class attribute...merely that it's ignored? May be worth adding a few words to some test method names, e.g., ClassAttribute_IsIgnored().

---

*[src/XliffForHtmlTests/TestExtractXliff.cs, line 170 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-Kr6HRJoefWi6vllRRUc:-Kr6HRJpbbwyCKtW4AGW:bqz061o) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/83ce89c92edcea7919d041d40a35e7342063413c/src/XliffForHtmlTests/TestExtractXliff.cs#L170)):*
> ```Smalltalk
> 			var extractor = HtmlXliff.Parse(@"<html>
> <body>
> <h2 class=""article-title"" i18n=""article-title"">Life and Habitat of the Marmot</h2>
> ```

Would it increase confidence that the right information is coming from the right source if the class and i18n attrs had different values?

---

*[src/XliffForHtmlTests/TestExtractXliff.cs, line 370 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-Kr6NvvT4_vMdWPv7EeK:-Kr6NvvT4_vMdWPv7EeL:b4v6cbp) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/83ce89c92edcea7919d041d40a35e7342063413c/src/XliffForHtmlTests/TestExtractXliff.cs#L370)):*
> ```Smalltalk
> 			Assert.AreEqual(2, source.ChildNodes.Count);
> 			int index = 0;
> 			foreach (XmlNode n0 in source.ChildNodes)
> ```

How is this (and similar) better than var n0 = source.ChildNodes[0]...n0 = source.ChildNodes[1]...? (Or of course you could declare a new n1, or even give meaningful names like textNode and imgNode.
(Now, changing them all at this point may be more trouble than it's worth, even if you agree...)

---

*[src/XliffForHtmlTests/TestExtractXliff.cs, line 463 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-Kr6UFToo9UUvoyU5Tgg:-Kr6UFToo9UUvoyU5Tgh:b-35d84h) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/83ce89c92edcea7919d041d40a35e7342063413c/src/XliffForHtmlTests/TestExtractXliff.cs#L463)):*
> ```Smalltalk
> 
> 		[Test]
> 		public void TestImgWithTitleAndAlt()
> ```

Actually it's the P element that has the title, which seems to be ignored very like the class attribute on the i18n element in a test above. I'm not very clear what extra thing this tests, though it can't hurt, I suppose.

---

*[src/XliffForHtmlTests/TestExtractXliff.cs, line 686 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-Kr6WV3zubbj6JtNJZtk:-Kr6WV3zubbj6JtNJZtl:b-e1m68y) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/83ce89c92edcea7919d041d40a35e7342063413c/src/XliffForHtmlTests/TestExtractXliff.cs#L686)):*
> ```Smalltalk
> 
> 		[Test]
> 		public void TestInlineSpans()
> ```

Is there something special about spans that deserves a separate test? If so it might be worth calling attention to with a comment.

---

*[src/XliffForHtmlTests/TestInjectXliff.cs, line 87 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-Kr6XyzmEydYgtnKYk16:-Kr6XyzmEydYgtnKYk17:bydhumy) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/83ce89c92edcea7919d041d40a35e7342063413c/src/XliffForHtmlTests/TestInjectXliff.cs#L87)):*
> ```Smalltalk
> 			Assert.AreEqual("be", paras[1].Attributes["xml:lang"].Value);
> 			Assert.AreEqual("Test 2", paras[1].Attributes["data-i18n"].Value);
> 			Assert.AreEqual("Гэта толькі тэст.", paras[1].InnerHtml);
> ```

The method name suggests that the main point of this test is that injection does not lose the br, but I don't see a check for this.

---

*[src/XliffForHtmlTests/TestInjectXliff.cs, line 155 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-Kr6YQueoUbCyIX7vdMG:-Kr6YQueoUbCyIX7vdMH:baisftc) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/83ce89c92edcea7919d041d40a35e7342063413c/src/XliffForHtmlTests/TestInjectXliff.cs#L155)):*
> ```Smalltalk
> 			Assert.AreEqual("de", headings[0].Attributes["xml:lang"].Value);
> 			Assert.AreEqual("article-title", headings[0].Attributes["class"].Value);
> 			Assert.AreEqual("article-title", headings[0].Attributes["i18n"].Value);
> ```

As before, this test would give me slightly more confidence if the class an i18n values were different.

---

*[src/XliffForHtmlTests/TestInjectXliff.cs, line 551 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-Kr6ZsJa6y_I84H2Jynf:-Kr6ZsJa6y_I84H2Jyng:b-74sxw6) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/83ce89c92edcea7919d041d40a35e7342063413c/src/XliffForHtmlTests/TestInjectXliff.cs#L551)):*
> ```Smalltalk
> Лицо</span>, в то время как ответы появятся в <span fontcolor=""#333399"">индиго
> лицо</span>.", paras[0].InnerHtml);
> 		}
> ```

Is it interesting for one of these tests to check what happens if the translator decides that the embedded structure must change? Suppose for example that the target language requires saying something like "Questions will appear in the face with the color green" and wants to make both "face" and "Green" (but not "with the color") have the color?

---

*[src/XliffForHtmlTests/TestInjectXliff.cs, line 827 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-Kr6bDg8oHOFqcCIsFe0:-Kr6bDg8oHOFqcCIsFe1:b-f58da3) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/83ce89c92edcea7919d041d40a35e7342063413c/src/XliffForHtmlTests/TestInjectXliff.cs#L827)):*
> ```Smalltalk
>   </body>
>  </file>
> </xliff>");
> ```

An important case that seems to belong here is where the xliff entirely lacks a trans-unit corresponding to an i18n in the source.
I guess you are checking (by counting attrs) that inject didn't tag the unchanged text with a spurious lang attribute. Is it an interestingly different case if the i18n element has a lang attribute in the html (which presumably would be replaced if there is a translation)?

---

*[src/XliffForHtmlTests/TestInjectXliff.cs, line 844 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-Kr6aoJ_Kk0-0PLSGSjf:-Kr6aoJ_Kk0-0PLSGSjg:b-jqryyi) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/83ce89c92edcea7919d041d40a35e7342063413c/src/XliffForHtmlTests/TestInjectXliff.cs#L844)):*
> ```Smalltalk
> 			Assert.AreEqual("Table.Cell-1.1", cells[0].Attributes["i18n"].Value);
> 			Assert.AreEqual("top", cells[0].Attributes["valign"].Value);
> 			Assert.AreEqual("Text in cell r1-c1", cells[0].InnerHtml);
> ```

It would be nice to draw attention to the key point with comments like "Original kept since target is empty/missing/whatever" and "no lang attr added"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-:-Kr6cpz6iXzouVvWIcL6:b-hzdj5u)*

**Comment by StephenMcConnel** [comment]
Review status: all files reviewed at latest revision, 20 unresolved discussions.

---

*[src/XliffForHtml/HtmlXliff.cs, line 39 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-Kr2ZneHRNHoqktRtI1G:-Kr78ScugsE4XQzdxhrh:b-896fix) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/83ce89c92edcea7919d041d40a35e7342063413c/src/XliffForHtml/HtmlXliff.cs#L39)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I find it very helpful in describing maps to say what the keys and values are (especially when they are generic things like strings).
</blockquote></details>

Done.

---

*[src/XliffForHtml/HtmlXliff.cs, line 164 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-Kr2b_iOVrDO9FeCNxWj:-Kr78z8jkW-5xXXLF2w_:b7ygcm5) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/83ce89c92edcea7919d041d40a35e7342063413c/src/XliffForHtml/HtmlXliff.cs#L164)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This variable name confused me, here and in similar places. It's true that it's the source element in the xliff file, but it's the OUTPUT of this method. Would it be too verbose to call it something like "sourceEltBeingCreated"?
</blockquote></details>

How about "newXliffSource" and "newXliffElement" (depending on context)

---

*[src/XliffForHtml/HtmlXliff.cs, line 175 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-Kr2cEYzJy636mwzGROP:-Kr7BJKnQcjLaHvDlq_G:b-896fix) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/83ce89c92edcea7919d041d40a35e7342063413c/src/XliffForHtml/HtmlXliff.cs#L175)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This compounds with the previous comment, but it's my impression that a fairly common convention is to put input arguments before outputs, in a method that uses some arguments to output results. E.g., File.Copy(source, dest). Here source is the element that gets modified using stuff from the second argument.
</blockquote></details>

Done.

---

*[src/XliffForHtml/HtmlXliff.cs, line 195 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-Kr2dLIduUfJVCpKMeul:-Kr7BI5NojtRBwkgQGl-:b-896fix) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/83ce89c92edcea7919d041d40a35e7342063413c/src/XliffForHtml/HtmlXliff.cs#L195)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Is it possible to summarize in a sentence or so what Oasis says about the purpose of "g" elements? (and "x" below)?
</blockquote></details>

Done.

---

*[src/XliffForHtml/HtmlXliff.cs, line 241 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-Kr2e9HJPcEd0e1lModX:-Kr7BjR1N69t6BaemRO7:bujrucx) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/83ce89c92edcea7919d041d40a35e7342063413c/src/XliffForHtml/HtmlXliff.cs#L241)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

That last argument seems misleading, since you haven't implemented it. Maybe it allows other code to be ready for that enhancement? Anyway, if there's a reason to keep it I think it should be commented.
</blockquote></details>

removed it.  leftover from initial coding when I wasn't sure what was being implemented.

---

*[src/XliffForHtml/HtmlXliff.cs, line 267 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-Kr2erWis2hhXHrSrMgk:-Kr7UN67hbRrf_U9nB5y:bujvmuh) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/83ce89c92edcea7919d041d40a35e7342063413c/src/XliffForHtml/HtmlXliff.cs#L267)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

What it actually does is check that all children that are elements are either inline or wrappers, which isn't quite what the comment says. Non-elements (even if not text or comments) are ignored.
What isn't clear and I think begs for explanation is WHY an element with no text is said to contain translatable text as long as it has no inline or wrapper elements. A div, for example, is apparently neither inline nor a wrapper (though depending on CSS, divs can certainly be inline, and they usually wrap things); so an element containing nothing but an empty div would evaluate as containing translatable text. If that's intentional I'd like it explained.
</blockquote></details>

That isn't exactly what is going on here: I scan text nodes first, and any noo-empty textnode triggers a true return.  Maybe I can rewrite this to make it clearer...

---

*[src/XliffForHtml/HtmlXliff.cs, line 348 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-Kr2hQwCe4OgSRtB94so:-Kr7eH2JAj4LorgW1w6F:b-9c1b6d) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/83ce89c92edcea7919d041d40a35e7342063413c/src/XliffForHtml/HtmlXliff.cs#L348)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Maybe explain a little more? I would expect, for example, that DIV and P would be considered wrappers, and maybe even span...they can certainly wrap a variety of other HTML elements.
</blockquote></details>

method no longer used, so removed, so doesn't need to be explained...  :-)

---

*[src/XliffForHtml/HtmlXliff.cs, line 495 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-Kr2lNhxqvx0SF3V2lYE:-Kr7eSQon2ax961gXU08:b3u3uoj) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/83ce89c92edcea7919d041d40a35e7342063413c/src/XliffForHtml/HtmlXliff.cs#L495)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Seems we should somehow warn the user about elements with data-i18n etc and nothing...not even original source?...in the xliff. Presumably they need to run extract again, or have altogether the wrong xliff?
</blockquote></details>

Hmm, that's a thought.  I'll make it a command line option. -v|--verbose

---

*[src/XliffForHtml/HtmlXliff.cs, line 570 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-Kr2iwult7M3RlXHjWwM:-Kr6ixzcOy461JiPPWqi:b-fmrm61) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/83ce89c92edcea7919d041d40a35e7342063413c/src/XliffForHtml/HtmlXliff.cs#L570)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Do we actually need to do this?
</blockquote></details>

Yes, the HTML parser gets totally confused by finding a random < character, even in places where you'd think it was quoted.

---

*[src/XliffForHtmlTests/TestExtractXliff.cs, line 29 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-Kr6G-M-7E1YUDk2xOr7:-KrCKjQCeO1xxz2-zRq1:b-v2ao13) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/83ce89c92edcea7919d041d40a35e7342063413c/src/XliffForHtmlTests/TestExtractXliff.cs#L29)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Surprises me that an XML file can have unescaped ampersands in an attribute value
</blockquote></details>

I had to change these to be encoded elsewhere to get things to work.  I forgot to change this comment.

---

*[src/XliffForHtmlTests/TestExtractXliff.cs, line 166 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-Kr6H9RukVXophKX8X2z:-KrCMKFe3WDttUoSwE-x:b444yvn) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/83ce89c92edcea7919d041d40a35e7342063413c/src/XliffForHtmlTests/TestExtractXliff.cs#L166)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It's not obvious what you're testing about the class attribute...merely that it's ignored? May be worth adding a few words to some test method names, e.g., ClassAttribute_IsIgnored().
</blockquote></details>

Apppended "IsIgnored" and "IsPreserved" to the two tests named TestClassAttribute

---

*[src/XliffForHtmlTests/TestExtractXliff.cs, line 170 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-Kr6HRJoefWi6vllRRUc:-KrCMUZrk_1rmWc8RJjy:b-896fix) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/83ce89c92edcea7919d041d40a35e7342063413c/src/XliffForHtmlTests/TestExtractXliff.cs#L170)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Would it increase confidence that the right information is coming from the right source if the class and i18n attrs had different values?
</blockquote></details>

Done.

---

*[src/XliffForHtmlTests/TestExtractXliff.cs, line 370 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-Kr6NvvT4_vMdWPv7EeK:-KrCdFz4jedhtPDKfmf9:bcwi0li) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/83ce89c92edcea7919d041d40a35e7342063413c/src/XliffForHtmlTests/TestExtractXliff.cs#L370)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

How is this (and similar) better than var n0 = source.ChildNodes[0]...n0 = source.ChildNodes[1]...? (Or of course you could declare a new n1, or even give meaningful names like textNode and imgNode.
(Now, changing them all at this point may be more trouble than it's worth, even if you agree...)
</blockquote></details>

For 3 or fewer child nodes, changing it might be clearer, so I'll do that.  Once you get to 4-8 children, the foreach/switch pattern seems just as clear to me as it allows capturing any commonalities.

---

*[src/XliffForHtmlTests/TestExtractXliff.cs, line 463 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-Kr6UFToo9UUvoyU5Tgg:-KrCMcWW_As3mfdu8DuO:b7kcnty) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/83ce89c92edcea7919d041d40a35e7342063413c/src/XliffForHtmlTests/TestExtractXliff.cs#L463)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Actually it's the P element that has the title, which seems to be ignored very like the class attribute on the i18n element in a test above. I'm not very clear what extra thing this tests, though it can't hurt, I suppose.
</blockquote></details>

It probably doesn't test anything different.  In the original code based on the OASIS recommendation, title is translatable and produced a trans-unit.  But the current program ignores it.  So the test probably doesn't add any new value.
I changed the test names to TestTitleAndAltAreIgnored and TestTitleAndAltArePreserved

---

*[src/XliffForHtmlTests/TestExtractXliff.cs, line 686 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-Kr6WV3zubbj6JtNJZtk:-KrCiLvbDahCvZimifQk:b-8b1ud1) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/83ce89c92edcea7919d041d40a35e7342063413c/src/XliffForHtmlTests/TestExtractXliff.cs#L686)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Is there something special about spans that deserves a separate test? If so it might be worth calling attention to with a comment.
</blockquote></details>

The main thing here is a random attribute value being preserved, not just lang.  I added a comment to this effect.

---

*[src/XliffForHtmlTests/TestInjectXliff.cs, line 87 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-Kr6XyzmEydYgtnKYk16:-KrCkzegXWmBuxSR8PWw:b-896fix) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/83ce89c92edcea7919d041d40a35e7342063413c/src/XliffForHtmlTests/TestInjectXliff.cs#L87)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

The method name suggests that the main point of this test is that injection does not lose the br, but I don't see a check for this.
</blockquote></details>

Done.

---

*[src/XliffForHtmlTests/TestInjectXliff.cs, line 155 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-Kr6YQueoUbCyIX7vdMG:-KrCMyzgo2Ork-bjQp2m:b-896fix) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/83ce89c92edcea7919d041d40a35e7342063413c/src/XliffForHtmlTests/TestInjectXliff.cs#L155)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

As before, this test would give me slightly more confidence if the class an i18n values were different.
</blockquote></details>

Done.

---

*[src/XliffForHtmlTests/TestInjectXliff.cs, line 551 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-Kr6ZsJa6y_I84H2Jynf:-KrCniX1m-lzlxsnOz-E:bbssgls) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/83ce89c92edcea7919d041d40a35e7342063413c/src/XliffForHtmlTests/TestInjectXliff.cs#L551)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Is it interesting for one of these tests to check what happens if the translator decides that the embedded structure must change? Suppose for example that the target language requires saying something like "Questions will appear in the face with the color green" and wants to make both "face" and "Green" (but not "with the color") have the color?
</blockquote></details>

hmm, the translator would really have to know what is going on with xml markup, but it is possible.  I can add a test to check this.  (TestTranslationChangesMarkup)

---

*[src/XliffForHtmlTests/TestInjectXliff.cs, line 827 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-Kr6bDg8oHOFqcCIsFe0:-KrCmA6gNi_L80C2oDTM:b2w8w4d) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/83ce89c92edcea7919d041d40a35e7342063413c/src/XliffForHtmlTests/TestInjectXliff.cs#L827)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

An important case that seems to belong here is where the xliff entirely lacks a trans-unit corresponding to an i18n in the source.
I guess you are checking (by counting attrs) that inject didn't tag the unchanged text with a spurious lang attribute. Is it an interestingly different case if the i18n element has a lang attribute in the html (which presumably would be replaced if there is a translation)?
</blockquote></details>

I'll remove the last trans-unit elements in this test.  It's already lacking a target element.  That will cover all 3 way to be missing a translation: empty target, missing target, and missing trans-unit.

---

*[src/XliffForHtmlTests/TestInjectXliff.cs, line 844 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-Kr6aoJ_Kk0-0PLSGSjf:-KrCnbJXsrsRH23R3AN8:b-896fix) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/83ce89c92edcea7919d041d40a35e7342063413c/src/XliffForHtmlTests/TestInjectXliff.cs#L844)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It would be nice to draw attention to the key point with comments like "Original kept since target is empty/missing/whatever" and "no lang attr added"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1)*

**Comment by JohnThomson** [comment]
:lgtm:

---

Review status: 13 of 15 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/XliffForHtml/HtmlXliff.cs, line 164 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-Kr2b_iOVrDO9FeCNxWj:-KrCzKs8LJmnG4NJp-at:brxp9sq) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/83ce89c92edcea7919d041d40a35e7342063413c/src/XliffForHtml/HtmlXliff.cs#L164)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

How about "newXliffSource" and "newXliffElement" (depending on context)
</blockquote></details>

Sounds good.

---

*[src/XliffForHtmlTests/TestExtractXliff.cs, line 370 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-Kr6NvvT4_vMdWPv7EeK:-KrCy967gjVFIu7o7M-x:bfglq8x) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/83ce89c92edcea7919d041d40a35e7342063413c/src/XliffForHtmlTests/TestExtractXliff.cs#L370)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

For 3 or fewer child nodes, changing it might be clearer, so I'll do that.  Once you get to 4-8 children, the foreach/switch pattern seems just as clear to me as it allows capturing any commonalities.
</blockquote></details>

There could still be a foreach that captures whatever is outside the switch, and what is inside it can't be common, can it? But up to you...only a suggestion. I'm glad to see the simpler ones improved.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/1#-:-KrCzFu_hifRDSOD-6tP:bnfp4nl)*

**Comment by JohnThomson** [comment]
Nice work. Thanks for your patience.

**Pull request merged**
