### PR TITLE
Handle lists produced by markdown-it for processing HTML

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/xliffforhtml/7)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Reviewed 3 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/XliffForHtml/HtmlXliff.cs, line 181 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/7#-KtXRLbw5erR1VS4AGYT:-KtXRLbxgc97A-qcVtkM:bl3v6p9) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/425f41abb73e3830c9030c2ec7016540303ed1d2/src/XliffForHtml/HtmlXliff.cs#L181)):*
> ```Smalltalk
> 					HtmlNode intlNode;		// If found, child node to store instead.
> 					var recurseNodes = new List<HtmlNode>();	// If found, child nodes to recurse on.
> 					if (IsListItemWithEmbeddedParagraph(node, out intlNode, recurseNodes))
> ```

Let's see if I have this straight. Special behavior happens if node is a list item (li) and its first child (other than whitespace) is a paragraph (p). We then discard the list item and just keep the results of processing the paragraph and any other non-white-space children of the list item.
The first thing that seems called for is a comment explaining why we need this strange special case.
I don't have ProcessHtmlElement in front of me so I'm not sure what undesirable thing it would do with a li containig another list. Maybe it's obvious if you can just refer to that method.

---

*[src/XliffForHtml/HtmlXliff.cs, line 206 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/7#-KtXQ3RJlKEAyig_4MyF:-KtXQ3RJlKEAyig_4MyG:bpml7hz) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/425f41abb73e3830c9030c2ec7016540303ed1d2/src/XliffForHtml/HtmlXliff.cs#L206)):*
> ```Smalltalk
> 		/// <param name="recurseNodes">output child nodes that need further processing (if returning true, else empty list)</param>
> 		/// <remarks>>
> 		/// recurseNodes must be set to a list before calling this method.  Any previous list content is cleared.
> ```

Since nothing is passed in through recurseNodes, why not just make it another out param? Rules out various mistakes and surprises.

---

*[src/XliffForHtmlTests/TestExtractXliff.cs, line 1225 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/7#-KtXU-7loELIanZOZT_o:-KtXU-7loELIanZOZT_p:bjesvsu) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/425f41abb73e3830c9030c2ec7016540303ed1d2/src/XliffForHtmlTests/TestExtractXliff.cs#L1225)):*
> ```Smalltalk
>   </ul>
>  </body>
> </html>");
> ```

Since the new code treats the first child paragraph specially, would it be helpful to test whatever behavior we expect if there is more than one child paragraph in a single list item? Or would they then require an i18n attribute each?

---

*[src/XliffForHtmlTests/TestExtractXliff.cs, line 1253 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/7#-KtXTAZZKWldXq03E4lJ:-KtXTAZZKWldXq03E4lK:buiq5sb) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/425f41abb73e3830c9030c2ec7016540303ed1d2/src/XliffForHtmlTests/TestExtractXliff.cs#L1253)):*
> ```Smalltalk
>   </body>
>  </file>
> </xliff>*/
> ```

I haven't yet actually figured out how this would be different without the new code. It might be worth pointing that out in a comment and, among the many asserts, highlighting the one(s) that verify the specific special behavior that nested lists call for. (Similarly below).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/7)*

**Comment by StephenMcConnel** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/XliffForHtml/HtmlXliff.cs, line 181 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/7#-KtXRLbw5erR1VS4AGYT:-KtXiFPIuILK0YXbPN_A:b-p98wdr) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/425f41abb73e3830c9030c2ec7016540303ed1d2/src/XliffForHtml/HtmlXliff.cs#L181)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Let's see if I have this straight. Special behavior happens if node is a list item (li) and its first child (other than whitespace) is a paragraph (p). We then discard the list item and just keep the results of processing the paragraph and any other non-white-space children of the list item.
The first thing that seems called for is a comment explaining why we need this strange special case.
I don't have ProcessHtmlElement in front of me so I'm not sure what undesirable thing it would do with a li containig another list. Maybe it's obvious if you can just refer to that method.

</blockquote></details>

I've revised the method signature (and changed the name of IsListItemWithEmbeddedParagraph to GetProperNodesForProcessing) to simplify its use, and added an extended description to the revised method.  I also added a comment here referring to that description.

---

*[src/XliffForHtml/HtmlXliff.cs, line 206 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/7#-KtXQ3RJlKEAyig_4MyF:-KtXiV5QDIClt8ISseaA:b-896fix) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/425f41abb73e3830c9030c2ec7016540303ed1d2/src/XliffForHtml/HtmlXliff.cs#L206)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Since nothing is passed in through recurseNodes, why not just make it another out param? Rules out various mistakes and surprises.
</blockquote></details>

Done.

---

*[src/XliffForHtmlTests/TestExtractXliff.cs, line 1225 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/7#-KtXU-7loELIanZOZT_o:-KtXrCmVqXb16c2TpSfw:bitnpuh) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/425f41abb73e3830c9030c2ec7016540303ed1d2/src/XliffForHtmlTests/TestExtractXliff.cs#L1225)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Since the new code treats the first child paragraph specially, would it be helpful to test whatever behavior we expect if there is more than one child paragraph in a single list item? Or would they then require an i18n attribute each?
</blockquote></details>

They would require an i18n attribute apiece, but markdown-it doesn't recognize attributes on a second (or following) paragraph inside a list item.  (The attributes never make it to the HTML.)  This could be a problem to be aware of if we get more complicated markdown files (and possibly a bug in markdown-it).  :-(
So far, none of our Markdown files have more than one paragraph inside a list item.

---

*[src/XliffForHtmlTests/TestExtractXliff.cs, line 1253 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/7#-KtXTAZZKWldXq03E4lJ:-KtY-JOPstIYmHl3-5tK:b-v8b8ih) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/425f41abb73e3830c9030c2ec7016540303ed1d2/src/XliffForHtmlTests/TestExtractXliff.cs#L1253)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I haven't yet actually figured out how this would be different without the new code. It might be worth pointing that out in a comment and, among the many asserts, highlighting the one(s) that verify the specific special behavior that nested lists call for. (Similarly below).
</blockquote></details>

I've added comments to the body of each of the new tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/7)*

**Comment by JohnThomson** [comment]
Much better, but I have more questions now that I have some idea what's going on. This same code will be used for non-markdown-generated HTML, right? Are there plausible cases where a hand-made HTML might trigger this behavior undesirably? What would it do, for example, to a list item with an initial paragraph where the i18n was already on the paragraph (and not the list item)? I guess that's covered by checking that the paragraph has no attributes. Do we actually check somewhere that the li DOES have i18n? What about a hand file where the paragraph at the start of the list item has no attrs but some spans within it have i18n?
Feel free to respond, "we don't have any silly cases like that so I don't think it's worth worrying about." :-)

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/XliffForHtml/HtmlXliff.cs, line 206 at r1](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/7#-KtXQ3RJlKEAyig_4MyF:-KtYO3ogCsQulXR3QywV:bse88vd) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/425f41abb73e3830c9030c2ec7016540303ed1d2/src/XliffForHtml/HtmlXliff.cs#L206)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Definitely makes it clearer...I like the other change too.

---

*[src/XliffForHtml/HtmlXliff.cs, line 235 at r2](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/7#-KtYM9hFKPwm8erqPT60:-KtYM9hFKPwm8erqPT61:b-rwvfob) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/322e60d4dcad36abcb58592bb235ba2b8f9bd8d8/src/XliffForHtml/HtmlXliff.cs#L235)):*
> ```Smalltalk
> 					if (child.Name.ToLowerInvariant() != "p" || child.Attributes.Count != 0)
> 						return node;
> 					intlNode = child;
> ```

From the comment above I expected to see code here that would copy the list item's i18n attribute to the paragraph. From the test, apparently it DOES work, but I can't see how.

---

*[src/XliffForHtml/HtmlXliff.cs, line 246 at r2](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/7#-KtYJ_Nl9cXFpInVfLPM:-KtYJ_Nl9cXFpInVfLPN:b-8xpm9a) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/322e60d4dcad36abcb58592bb235ba2b8f9bd8d8/src/XliffForHtml/HtmlXliff.cs#L246)):*
> ```Smalltalk
> 				}
> 			}
> 			return intlNode;
> ```

What if there are no non-whitespace children? Probably pathological, but will the caller cope with the return value being null? The comment suggests that this is not supposed to be possible.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/7#-:-KtYKxDNJUt61AEeKyob:b-tzwaca)*

**Comment by StephenMcConnel** [comment]
We only get into this code if the li element has been determined to have an i18n attribute.
Markdown doesn't produce spans.  If the user marks the paragraph (p element) with an i18n attribute, and then spans (span elements) inside the paragraph have an i18n attribute, well, that's a broken condition that already wasn't being handled.  Once we detect that an element has an i18n attribute, and appears to have translatable text inside it somewhere, we chunk out a trans-unit with the source element filled in, and stop processing that element.  We depend on humans to be careful writing raw HTML or PUG to avoid situations that break the recursive processing model.  This new code is solely to deal with the fact Markdown-it processing of "*" list items embeds the text in paragraphs but places the i18n attribute on the parent li element.
I think this may be a long winded way of saying "we don't have silly cases like that..."

---

Review status: 2 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/XliffForHtml/HtmlXliff.cs, line 235 at r2](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/7#-KtYM9hFKPwm8erqPT60:-KtYSMLIAF-XSNbQKint:b-ev2vu3) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/322e60d4dcad36abcb58592bb235ba2b8f9bd8d8/src/XliffForHtml/HtmlXliff.cs#L235)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

From the comment above I expected to see code here that would copy the list item's i18n attribute to the paragraph. From the test, apparently it DOES work, but I can't see how.
</blockquote></details>

we don't want two copies of the i18n attribute in the HTML.  it would just confuse readers I think.  I expanded/revised my commentary a bit.

---

*[src/XliffForHtml/HtmlXliff.cs, line 246 at r2](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/7#-KtYJ_Nl9cXFpInVfLPM:-KtYT7DNviR2n70CtsLA:b-oslk2q) ([raw file](https://github.com/sillsdev/xliffforhtml/blob/322e60d4dcad36abcb58592bb235ba2b8f9bd8d8/src/XliffForHtml/HtmlXliff.cs#L246)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

What if there are no non-whitespace children? Probably pathological, but will the caller cope with the return value being null? The comment suggests that this is not supposed to be possible.
</blockquote></details>

Shouldn't be possible (due to the check for "translatable text" made before getting here in the code), but trivial to check for.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/7#-:-KtYQt0yxYrK6PETn-vN:b-ize3yt)*

**Comment by JohnThomson** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/xliffforhtml/7#-:-KtYe8vT80rGvf31gs1E:bnfp4nl)*

**Pull request merged**
